### ISSUE TITLE
Crash on some Repositories on Fedora 32

### ISSUE THREAD

**Issue by kalkin** [kalkin/git-log-viewer#13]
Happens on some repositories only on Fedora 32 with python 3.8. Works fine on my Gentoo installation with python 3.7

```
Traceback (most recent call last):
  File "/home/user/.local/bin/glv", line 11, in <module>
    load_entry_point('git-log-viewer==1.5.0', 'console_scripts', 'glv')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/.local/lib/python3.8/site-packages/glv/main.py", line 115, in <module>
    HISTORY_CONTAINER = HistoryContainer(KB, REPO, right_margins=MARGINS)
  File "/home/user/.local/lib/python3.8/site-packages/glv/ui/history.py", line 476, in __init__
    log_view = HistoryControl(search.control,
  File "/home/user/.local/lib/python3.8/site-packages/glv/ui/history.py", line 367, in __init__
    self.content = History(repo)
  File "/home/user/.local/lib/python3.8/site-packages/glv/ui/history.py", line 168, in __init__
    self.fill_up(utils.screen_height())
  File "/home/user/.local/lib/python3.8/site-packages/glv/ui/history.py", line 356, in fill_up
    if len(commit.author_date()) > self.date_max_len:
  File "/home/user/.local/lib/python3.8/site-packages/glv/__init__.py", line 104, in author_date
    return babel.dates.format_timedelta(delta, format=_format)
  File "/home/user/.local/lib/python3.8/site-packages/babel/dates.py", line 944, in format_timedelta
    pattern = patterns[plural_form]
  File "/home/user/.local/lib/python3.8/site-packages/babel/localedata.py", line 218, in __getitem__
    orig = val = self._data[key]
KeyError: 'other'
```

**Comment by kalkin** [comment]
Looks like [python-babel/babel](https://github.com/python-babel/babel/) 2.8.0 can't handle timedeltas < 1 min anymore. Just another case of “I-can't-possibly-be-the-only-guy-using-this-library” *sigh*. Need to create a reproducible example and open an issue.
